sporocilo = 'HPBKVLZRSOVGZYLBGBDMFDRHRMRHSPBKHZY VBHDBGBJ RYSNBSUB PKSNHPOBFLBQYHKYBMPHRDBSUBZAGHPR WRBGV BV ZAGK NBQHRYBKHZY VR WRBGKKSVNHPOBRSBGBV OMAGVBDLDR JBRY BMPHRDBJGLBF BDHPOA BA RR VDBRY BJSDRBKSJJSPBZGHVDBSUBA RR VDBRVHZA RDBSUBA RR VDBJHWRMV DBSUBRY BGFSI BGPNBDSBUSVRYBRY BV K HI VBN KHZY VDBRY BR WRBFLBZ VUSVJHPOBGPBHPI VD BDMFDRHRMRHSP'
fnAnaliza(sporocilo,1);
kljuc =   ['E','L',' ','-','S','-','B','A','I','V','M','C','Y','U','D','G','N','W','T','O','-','F','R','X','-','H','P'];
fnSubstitucija(sporocilo,1,kljuc)
